### ISSUE TITLE
Divergence in classification between digits and GRE

### ISSUE THREAD

**Issue by rperdon** [NVIDIA/gpu-rest-engine#27] opened 2017-12-20 21:57 UTC
When running a digits exported model into the GRE, I am getting some divergence in the values of the classification when compared to Digits. In some cases, it is flipping the classification completely to the opposite classification with regards to a binary classifier. When using the Digits REST (non GRE), I am getting identical classifications to Digits so I am wondering where the divergence lies. 

I altered the first line in the deploy.prototext of my exported model from
input: "data"
input_shape {
  dim: 1
  dim: 3
  dim: 227
  dim: 227
}

To 

name: "AlexNet"
layer {
  name: "data"
  type: "Input"
  top: "data"
  input_param { shape: { dim: 1 dim: 3 dim: 227 dim: 227 } }
}

I mimicked this based off the deploy.prototext in the GRE model folder and altered the shape to coincide with my model.

I saw in a previous issue that there was a problem with varying confidence and am wondering if it is related. https://github.com/NVIDIA/gpu-rest-engine/issues/3

**Comment by flx42** [comment] 2017-12-20 22:59
Are you using the caffe version of GRE?

**Comment by rperdon** [comment] 2017-12-20 23:40
I am using the caffe version of GRE.

**Comment by flx42** [comment] 2017-12-21 01:59
The issue you mentioned had varying confidence results for the same image. Is this the case?

**Comment by rperdon** [comment] 2017-12-21 02:20
It was actually the 2nd post of that thread that piqued my interest regarding a difference in confidence results.

**Comment by flx42** [comment] 2017-12-21 02:26
Ah yes. It might be the preprocessing that's the culprit. Unfortunately the current code is not very generic to this regard.

**Comment by rperdon** [comment] 2017-12-21 03:12
I'm hoping we can identify the cause of the divergence as the GRE would work perfectly for what I need it to do.

**Comment by flx42** [comment] 2017-12-21 05:00
Unfortunately, it's challenging to debug since I don't have access to your model. Do you know what DIGITS is using in the pre-processing steps? Crops? resizes? Augmentation?

**Comment by rperdon** [comment] 2017-12-21 14:55
For the Model portion; Subtract Mean, no crop option. On the Database, the default it had was squash image size 256x256, color image encoding png. On the deploy.prototxt, the dimensions are as above for the exported model.

**Comment by rperdon** [comment] 2017-12-28 19:02
Any thoughts on this? I'm hoping Griffin and I can work out a solution with you.

**Comment by flx42** [comment] 2017-12-28 19:05
If you pre-resize the images to the right size (227x227?) before sending them to GRE, does it change anything?

**Comment by rperdon** [comment] 2017-12-28 19:12
Just toss them into photoshop, do a bilinear resize to 227x227 for all the images prior to GRE? In the classification code you have, do you use opencv for that part? I wonder if I can do it there before its classified.

**Comment by flx42** [comment] 2017-12-28 19:13
Yes I use OpenCV for that.
For now I'm just trying to find out if it's the resize that's the culprit. So take this 227x227 image and send it to both GRE and DIGITS.

**Comment by rperdon** [comment] 2017-12-28 19:14
I can test it out.

**Comment by rperdon** [comment] 2017-12-28 20:15
Image blilinear resize to 227x227

Digits classify.py:
0: 21.5443
1: 78.4557%

GRE:  
0: 0.5819
1: 0.4181
-----------------------
Digits unaltered image:
0: 21.8740
1: 78.1260

GRE unaltered image:
0: 0.553
1: 0.447

I find it interesting that a pre-resize of the image alters the values in Digits as well.

**Comment by rperdon** [comment] 2017-12-28 21:01
I will try a different approach; I'm thinking since I've worked a lot with the classify.py file from digits, I can try to modify that to see if I can reproduce the same value that the GRE produces.

**Comment by flx42** [comment] 2017-12-28 21:20
Ok. And it should be pretty straightforward to compare the pre-processing steps from DIGITS and gpu-rest-engine. It's just a few lines of Python/C++ code.
I think the resize is the only piece that might differ (since you can have multiple interpolation algorithms). The other steps should produce the same results, but since we still have a divergence, it's probably that it's not the same operations that are used.

**Comment by rperdon** [comment] 2017-12-28 21:32
Griffin has mentioned something about mapping values or weights being done differently with regards to DeepDetect. I'm wondering if something similar is happening here. I'll have to check back with him on this idea of what was happening.

**Comment by laceyg** [comment] 2017-12-28 21:52
Originally I thought there may an issue with something like dimension ordering (e.g. NKHW) but it seems unlikely that this is the culprit here.  I agree with @flx42 that something like resizing may be the problem - something like a different interpolation being used.

Let me see if I can reproduce this divergence with a simple example.

**Comment by flx42** [comment] 2017-12-28 23:18
I think we ruled out the resize now, since @rperdon tried with images that are already at 227x227. So the culprit is probably something else: mean subtraction, cropping, etc.

**Comment by rperdon** [comment] 2017-12-29 14:58
I have played further with some other images which were flipping the classifications. 

I resized in photoshop, baseline compression, (previous was png, no compression), bilinear to 227x227. 

Digits: 
0 95.79
1 4.21

GRE 
0 0.501
1 0.499

Unaltered: (1024x1024)
Digits: 
0 92.2
1 7.8

GRE
0 0.042
1 0.958

I made a mistake in the Digits classification example.py compared to Digits REST comparisons I was using: The default is squash and subtract pixel for Digits Classification example.py while in Digits I was working with subtract image. The model I am working as with the desired results is running from Digits REST, not the example.py so I will have to do some work to ensure that example.py is modified to represent what Digits is doing before being able to properly compare resizing code changes.

**Comment by rperdon** [comment] 2017-12-29 15:23
https://github.com/NVIDIA/DIGITS/issues/169

I think this may provide key insight to adapting GRE to work like Digits. I'm just wrapping my head around the implications and hopefully we can sort this out.

Edit: I retrained the model using mean pixel instead of mean image then reloaded the model into GRE.
GRE was still consistent with the images it flipped for classifications. So image vs pixel isn't the missing link.

**Comment by rperdon** [comment] 2018-01-02 19:42
I did a test of the differences of the resize function of PIL which the classification example of Digits uses and OpenCV's resize function:

min; mean, max:

OpenCV
(15, 160.10562983950786, 254)
SciPy - used by PIL
(15, 160.21342674351661, 254)

Noting a discrepancy in the mean value of the image, I think this is one part of the divergence problem. I do suspect more reasons but to me its feeling like there is a particular "order" of operations that each image load, mean subtract (pixel/image), crop, resize order that there is no defined standard to follow. 

I thought this was an interesting read about "unknown" operations done by various resize operations of matrices. In this example, opencv vs matlab

https://stackoverflow.com/questions/21997094/why-opencv-cv2-resize-gives-different-answer-than-matlab-imresize

**Comment by flx42** [comment] 2018-01-02 22:13
I would expect that a difference in resize could explain a divergence in the order of 10^-2 or 10^-3, not more.

**Comment by rperdon** [comment] 2018-01-03 18:43
I did some further testing between scipy, opencv and skimage and found each produced different results leading me to believe something like anti-aliasing could be a problem. 

Digits classification example uses scipy which its resize function is deprecated now.

https://docs.scipy.org/doc/scipy/reference/generated/scipy.misc.imresize.html

I want to read more into opencv's and skimage to see if I can get them to generate the same results.

**Comment by rperdon** [comment] 2018-01-04 14:57
Some more reading info on differences. 

short version: scipy does a conversion to uint8, is now deprecated
Something with a 90% accuracy in scipy resize, drops to 60% with skimage resize and drops to 53% accuracy in opencv.

**Comment by flx42** [comment] 2018-07-20 20:11
There has been other back and forth on email about this issue, I will close this.

**Closed by flx42** 2018-07-20 20:11 UTC
